### PR TITLE
Make DOMDocument configurable

### PR DESCRIPTION
**Pull request by ManuDoni**
Add parameter $options in SchemaValidator constructor.
This make possible validate big files.

### CODE REVIEW

**Comment by eclipxe13** [comment]
Welcome and thanks!

Looks like I could not replicate the test `testValidateLargeXmlWithoutCorrectOptions` On My Machine™. Neither Travis-CI builds are passing on this test.

I like the idea about passing more options to `loadXML`.

Can you make test pass?



But taking a step back... the code smell at the point that `__constructor` is creating the `DOMDocument`, why don't just receive it? Why it has to receive 12MB just to create the `DOMDocument`?

In that case, you can build the `DOMDocument` with any option you like and then just create the validator like `$validator = new SchemaValidator($myHugeDOMDocument)`.

I'm not against changing the constructor to `string|DOMDocument`.

Would you like to PR about this last approach?

**Comment by ManuDoni** [comment]
Sorry, on my machines it doesn't fail. I'm on Windows 10 with PHP 7.1. Maybe 13 MB isn't big enough for your machine and for Travis-CI.

> Why it has to receive 12MB just to create the DOMDocument?

The amount of occupied RAM doesn't change if you create a huge DOMDocument and pass it to the constructor or if you pass the huge content.

**Comment by eclipxe13** [comment]
> The amount of occupied RAM doesn't change if you create a huge DOMDocument and pass it to the constructor or if you pass the huge content.

At least is not duplicated as `DOMDocument` argument would pass by reference and `string` would pass by value (making a copy).

**Comment by eclipxe13** [comment]
I think the approach to create a `SchemaValidator` using a `DOMDocument` object fixed the original issue, I'm closing this PR.

**Comment by ManuDoni** [comment]
I never thanked you for this, at that time i was working on it but you beat me by a few hours.

**Pull request closed without merging**
